version: '3.5'
services:
  java-srv:
    build: java-srv
    command: sh -c "/wait && gradle run"
    environment:
      - WAIT_HOSTS=db:6080
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: dgraph/dgraph
    command: dgraph zero --bindall


